<?xml version="1.0"?>
<!DOCTYPE design_config [
 <!ELEMENT design_config (icons, skill_icon_sets+, icon_image_sets,
					common_images?, color_types, design+)>
  <!ELEMENT icons (icon+)>
  <!ELEMENT icon EMPTY>
  <!ELEMENT skill_icon_sets (skill_set+)>
  <!ELEMENT skill_set (icon_group+)>
  <!ELEMENT icon_group (icon+)>
  <!ELEMENT icon_image_sets (icon_image_set+)>
  <!ELEMENT icon_image_set (preview_image, image*)>
  <!ELEMENT common_images (image+)>
  <!ELEMENT color_types (color_type+)>

  <!ELEMENT design (preview_image, colors, base_images?, image_sets,
	allowed_skill_icon_sets+, allowed_icon_image_sets*, color_scheme+)>
  <!ELEMENT colors (color*)>
  <!ELEMENT base_images (image+)>
  <!ELEMENT image_sets (set_images, image_set+)>
  <!ELEMENT set_images (image+)>
  <!ELEMENT image_set (image*)>
  <!ELEMENT allowed_skill_icon_sets (set+)>
  <!ELEMENT allowed_icon_image_sets (set+)>
  <!ELEMENT set EMPTY>
  <!ELEMENT color_scheme (color*)>
  <!ELEMENT color_type EMPTY>
  <!ELEMENT image EMPTY>
  <!ELEMENT color EMPTY>
  <!ELEMENT preview_image EMPTY>

  <!ATTLIST icon id CDATA #REQUIRED>
  <!ATTLIST icon url_param CDATA #IMPLIED>
  <!ATTLIST icon rtype CDATA #IMPLIED>
  <!ATTLIST icon platform CDATA #IMPLIED>
  <!ATTLIST icon label CDATA #IMPLIED>
  <!ATTLIST icon tip CDATA #IMPLIED>
  <!ATTLIST icon help CDATA #IMPLIED>
  <!ATTLIST icon demo_available CDATA #IMPLIED>
  <!ATTLIST icon new_window CDATA #IMPLIED>

  <!ATTLIST icon_group id CDATA #REQUIRED>
  <!ATTLIST icon_group label CDATA #REQUIRED>

  <!ATTLIST skill_icon_sets account_type CDATA #REQUIRED>
  <!ATTLIST skill_set id CDATA #REQUIRED>
  <!ATTLIST skill_set label CDATA #REQUIRED>

  <!ATTLIST icon_image_sets base_dir CDATA #IMPLIED>

  <!ATTLIST icon_image_set id CDATA #REQUIRED>
  <!ATTLIST icon_image_set label CDATA #REQUIRED>
  <!ATTLIST icon_image_set dir CDATA #IMPLIED>

  <!ATTLIST common_images base_dir CDATA #IMPLIED>

  <!ATTLIST color_type id CDATA #REQUIRED>
  <!ATTLIST color_type label CDATA #REQUIRED>

  <!ATTLIST design id CDATA #REQUIRED>
  <!ATTLIST design label CDATA #REQUIRED>
  <!ATTLIST design template_dir CDATA #REQUIRED>
  <!ATTLIST design default_color_scheme CDATA #REQUIRED>

  <!ATTLIST allowed_skill_icon_sets account_type CDATA #REQUIRED>
  <!ATTLIST allowed_skill_icon_sets default CDATA #IMPLIED>
  <!ATTLIST allowed_icon_image_sets account_type CDATA #REQUIRED>
  <!ATTLIST allowed_icon_image_sets default CDATA #IMPLIED>

  <!ATTLIST image_sets base_dir CDATA #IMPLIED>

  <!ATTLIST image id CDATA #REQUIRED>
  <!ATTLIST image file CDATA #REQUIRED>
  <!ATTLIST image alt_file CDATA #IMPLIED>
  <!ATTLIST image rtl_file CDATA #IMPLIED>
  <!ATTLIST image rtl_alt_file CDATA #IMPLIED>
  <!ATTLIST image width CDATA #REQUIRED>
  <!ATTLIST image height CDATA #REQUIRED>

  <!ATTLIST preview_image file CDATA #REQUIRED>
  <!ATTLIST preview_image alt_file CDATA #IMPLIED>
  <!ATTLIST preview_image rtl_file CDATA #IMPLIED>
  <!ATTLIST preview_image rtl_alt_file CDATA #IMPLIED>
  <!ATTLIST preview_image width CDATA #REQUIRED>
  <!ATTLIST preview_image height CDATA #REQUIRED>

  <!ATTLIST base_images base_dir CDATA #REQUIRED>

  <!ATTLIST image_set id CDATA #REQUIRED>
  <!ATTLIST image_set label CDATA #REQUIRED>
  <!ATTLIST image_set dir CDATA #REQUIRED>

  <!ATTLIST set id CDATA #REQUIRED>

  <!ATTLIST color_scheme id CDATA #REQUIRED>
  <!ATTLIST color_scheme image_set CDATA #REQUIRED>
  <!ATTLIST color_scheme icon_image_set CDATA #REQUIRED>
  <!ATTLIST color_scheme label CDATA #REQUIRED>

  <!ATTLIST color id CDATA #REQUIRED>
  <!ATTLIST color value CDATA #REQUIRED>
]>

<design_config>

<icons>
    <!--
    The rtype attribute is used to make decision whether or not the icon will be
    drawn. It may include H-Sphere resource type names delimited by
    charachters ';' and ',' as follows:
    - res1 - simple resource type, icon will appear if the resource is available;
    - res1,res2,res3 - group of resources where all of them must be available to
    show an icon(operation 'AND');
    - res1; res2; res3 - icon will be shown if any of the resources is available
    (operation 'OR');
    - res1,res2; res3,res4; res5,res6 - combination of groups where an icon will
    be shown if any of the groups - res1,res2 or res3,res4 or res5,res6 includs
    both available resources.
    -->
  <icon id="cgiwiz_phpbb" url_param="template_name=quick/choice_phpbb.html&amp;sname=bbs"
	rtype="phpbb" platform=""
	label="quick.quickview.cgiwiz_phpbb" tip="quick.quickview.cgiwiz_phpbb"
	help=""/>
  <icon id="db_ms" url_param="template_name=quick/choice_mssql.html"
	rtype="MSSQL" platform=""
	label="quick.quickview.mssql" tip="quick.quickview.altmssql"
	help=""/>
  <!-- MS SQL manager-->
  <icon id="db_msmanager" url_param="template_name=MSSQL/manager.html"
	  rtype="MSSQL" platform="win2k"
	  label="quick.quickview.mssqlmanager" tip="quick.quickview.altmssqlmanager"
	  help=""/>
  <!-- end of MS SQL manager-->
  <icon id="db_my" url_param="template_name=quick/choice_mysql.html"
	rtype="MySQL" platform=""
	label="quick.quickview.mysql" tip="quick.quickview.altmysql"
	help=""/>
  <icon id="db_pg" url_param="template_name=quick/choice_pgsql.html"
	rtype="pgsql" platform=""
	label="quick.quickview.pgsql" tip="quick.quickview.altpgsql"
	help=""/>
  <icon id="db_odbc" url_param="template_name=odbc/list.html"
	rtype="odbc" platform="win2k"
	label="quick.quickview.odbc" tip="quick.quickview.odbc"
	help=""/>
  <icon id="db_phpmyadmin" url_param="template_name=quick/choice_phpmyadmin.html"
        rtype="MySQL" platform=""
        label="quick.quickview.phpmyadmin" tip="quick.quickview.phpmyadmin"
        help=""/>
  <icon id="db_phppgadmin" url_param="template_name=quick/choice_phppgadmin.html"
        rtype="pgsql" platform=""
        label="quick.quickview.phppgadmin" tip="quick.quickview.phppgadmin"
        help=""/>
  <icon id="info_bill" url_param="template_name=billing/view.html"
	rtype="BILLING;WITHOUT_BILLING" platform=""
	label="label.bi" tip="label.bi" help=""/>
  <icon id="info_contact" url_param="template_name=billing/cinfo_view.html"
	rtype="" platform=""
	label="label.ci" tip="label.ci" help=""/>
  <icon id="info_invoice" url_param="template_name=billview/list.html"
	rtype="BILLING;WITHOUT_BILLING" platform=""
	label="label.online_invoice" tip="label.online_invoice"
	help=""/>
  <icon id="info_price" url_param="template_name=billing/price.html"
	rtype="BILLING" platform=""
	label="label.price" tip="label.price"
	help=""/>
  <icon id="info_suminvoice" url_param="template_name=sumbill/list.html"
	rtype="BILLING;WITHOUT_BILLING" platform=""
	label="label.suminvoice" tip="label.suminvoice"
	help=""/>
  <icon id="info_mback" url_param="template_name=billing/money_confirm.html"
	rtype="BILLING,MONEY_BACK" platform=""
	label="label.money_back" tip="label.money_back"
	help=""/>
  <icon id="main_ch_pass" url_param="template_name=quick/password_form.html"
	rtype="!bizorg" platform=""
	label="quick.quickview.changepsw"
	tip="quick.quickview.changepsw" help=""/>
  <icon id="msexchange_ch_pass" url_param="template_name=misc/password_form.html"
	rtype="bizorg" platform="msexchange"
	label="quick.quickview.changepsw"
	tip="quick.quickview.changepsw" help=""/>
  <icon id="main_ch_acc" url_param="template_name=misc/choose_account.html"
	rtype="!bizorg" platform=""
	label="quick.quickview.changeacc"
	tip="quick.quickview.changeacc" help=""/>
  <icon id="main_add_acc" url_param="template_name=misc/add_accounts.html"
	rtype="!bizorg" platform=""
	label="quick.quickview.add_acc"
	tip="quick.quickview.add_acc" help=""/>
  <icon id="main_domainman" url_param="template_name=domain/list.html"
	rtype="domain; nodomain; service_domain; 3ldomain; parked_domain" platform="unix;win2k;mail_only"
	label="quick.quickview.qadomains"
	tip="quick.quickview.qadomains" help=""/>
  <icon id="msexchange_users" url_param="template_name=msexchange/users.html"
	rtype="bizuser" platform="msexchange"
	label="quick.msexchange.mailboxes"
	tip="quick.msexchange.mailboxes" help=""/>
  <icon id="msexchange_domains" url_param="template_name=msexchange/smtpdomains.html"
	  rtype="domain" platform="msexchange"
	  label="quick.msexchange.domains"
	  tip="quick.msexchange.domains" help=""/>
  <icon id="msexchange_dns_settings" url_param="template_name=msexchange/dns_edit.html"
	  rtype="domain" platform="msexchange"
	  label="quick.msexchange.dns_settings"
	  tip="quick.msexchange.domains" help=""/>
  <icon id="msexchange_dl" url_param="template_name=msexchange/dl.html"
	  rtype="distribution_list" platform="msexchange"
	  label="quick.msexchange.dlists"
	  tip="quick.msexchange.dlists" help=""/>
  <icon id="ws_frontpage" url_param="template_name=quick/choice_fpage.html"
	rtype="frontpage" platform=""
	label="quick.quickview.fp" tip="quick.quickview.fp"
	help=""/>
  <icon id="main_websets" url_param="template_name=quick/choice_hosting.html"
        rtype="hosting" platform=""
        label="quick.quickview.weboptions"
        tip="quick.quickview.altweboptions" help=""/>
  <icon id="ftp_virt" url_param="template_name=ftp/ftp.html"
	rtype="ftp_vhost" platform="unix"
	label="quick.quickview.ftp" tip="quick.quickview.ftp"
	help=""/>
  <icon id="ftp_man" url_param="template_name=unixuser/view.html"
	rtype="unixuser" platform="unix"
	label="quick.quickview.ftpman"
	tip="quick.quickview.ftpman" help=""/>
  <icon id="ftp_man_w2k" url_param="template_name=winuser/view.html"
	rtype="unixuser" platform="win2k"
	label="quick.quickview.ftpman"
	tip="quick.quickview.ftpman" help=""/>
  <icon id="ftp_anon" url_param="template_name=winftp/ftp.html"
	rtype="ftp_vhost_anonymous" platform="win2k"
	label="quick.quickview.ftpanon"
	tip="quick.quickview.ftpanon" help=""/>
  <icon id="mail_man" url_param="template_name=email/list2.html"
	rtype="mail_service" platform=""
	label="quick.quickview.email" tip="quick.quickview.altemail"
	help=""/>
  <icon id="mail_web" url_param="template_name=quick/webmail.html"
	rtype="mail_service" platform=""
	label="quick.quickview.webmail"
	tip="quick.quickview.webmail" help=""
	/>
  <icon id="mail_auto" url_param="template_name=email/list2.html"
	rtype="disable" platform=""
	label="quick.quickview.autoresponders"
	tip="quick.quickview.autoresponders" help=""/>
  <icon id="mail_list" url_param="template_name=email/list2.html"
	rtype="disable" platform=""
	label="quick.quickview.mail_list"
	tip="quick.quickview.mail_list" help=""/>
  <icon id="mail_filter" url_param=""
	rtype="disable" platform=""
	label="quick.quickview.mail_filter"
	tip="quick.quickview.mail_filter" help=""/>
  <icon id="ec_miva" url_param="template_name=quick/choice_miva.html"
	rtype="miva" platform=""
	label="quick.quickview.miva" tip="quick.quickview.altmiva"
	help=""/>
  <icon id="ec_os" url_param="template_name=quick/choice_oscommerce.html"
	rtype="oscommerce" platform=""
	label="quick.quickview.oscommerce" tip="quick.quickview.oscommerce"
	help=""/>
  <icon id="tool_ss" url_param="template_name=quick/choice_sitebuilder.html"
	rtype="sitestudio" platform=""
	label="quick.quickview.sitestudio"
	tip="quick.quickview.altsitestudio" help=""/>
  <icon id="tool_fileman" url_param="template_name=quick/choice_webshell.html"
	rtype="unixuser,WEBSHELL" platform="unix"
	label="quick.quickview.filemanager"
	tip="quick.quickview.filemanager" help=""
	new_window="1"/>
  <icon id="tool_webshell3" url_param="template_name=quick/choice_webshell3.html"
	rtype="unixuser,WEBSHELL3" platform=""
	label="quick.quickview.webshell3"
	tip="quick.quickview.filemanager3" help=""
	new_window="1"/>
  <icon id="tool_webshell4" url_param="template_name=quick/choice_webshell4.html"
	rtype="unixuser,WEBSHELL4" platform=""
	label="quick.quickview.webshell4"
	tip="quick.quickview.filemanager4" help=""
	new_window="1"/>
<!--
  <icon id="tool_webprotect" url_param="template_name=quick/choice_htprotect.html"
	rtype="unixuser,WEBSHELL" platform="unix"
	label="quick.quickview.webprotect"
	tip="quick.quickview.webprotect" help=""
	new_window="1"/>
-->
  <icon id="tool_stats" url_param="template_name=quick/choice_stat.html"
	rtype="webalizer; modlogan; urchin; awstats" platform=""
	label="quick.quickview.stats"
	tip="quick.quickview.stats" help=""/>
  <icon id="tool_logman" url_param="template_name="
	rtype="disable" platform=""
	label="quick.quickview.logman"
	tip="quick.quickview.logman" help=""/>
  <icon id="tool_cron" url_param="template_name="
	rtype="disable" platform=""
	label="quick.quickview.cron"
	tip="quick.quickview.cron" help=""/>
  <icon id="tool_pgp" url_param="template_name="
	rtype="disable" platform=""
	label="quick.quickview.pgp"
	tip="quick.quickview.pgp" help=""/>
  <icon id="tool_java" url_param="template_name="
	rtype="disable" platform=""
	label="quick.quickview.java"
	tip="quick.quickview.java" help=""/>
  <icon id="tool_trace" url_param="template_name=domain/traceroute.html"
        rtype="" platform=""
        label="quick.quickview.trace"
        tip="quick.quickview.trace" help=""/>
  <icon id="tool_kanoodle" url_param="template_name=misc/kanoodle.html"
        rtype="kanoodle" platform=""
        label="icon.quick.kanoodle_l" tip="icon.quick.kanoodle_t"
        help=""/>
  <icon id="tool_sitetoolbox" url_param="template_name=misc/sitetoolbox.html"
        rtype="SITETOOLBOX" platform=""
        label="icon.quick.sitetoolbox_l" tip="icon.quick.sitetoolbox_t"
        help=""/>
  <icon id="sup_guide" url_param="http://www.psoft.net/HSdocumentation/user/index.html"
	rtype="disable" platform=""
	label="quick.quickview.sup_guide" tip="quick.quickview.sup_guide"
	help=""/>
  <icon id="sup_forum" url_param=""
	rtype="disable" platform=""
	label="quick.quickview.sup_forum" tip="quick.quickview.sup_forum"
	help=""/>

  <icon id="job_admin" url_param="template_name=background/job_admin.html"
    rtype="reseller_su" platform=""
    label="quick.quickview.background_man" tip="quick.quickview.background_man"
    help=""/>

  <icon id="job_alive" url_param="template_name=background/job_alive.html"
    rtype="reseller_su" platform=""
    label="quick.quickview.background_alive" tip="quick.quickview.background_alive"
    help=""/>

  <icon id="config_tt" url_param="template_name=tt/config_tt.html"
        rtype="tt" platform=""
	label="quick.quickview.config_tt" tip="quick.quickview.config_tt"
	help=""/>
  <icon id="tt_stats" url_param="template_name=tt/tt_stats.html"
        rtype="tt" platform=""
	label="quick.quickview.tt_stats" tip="quick.quickview.tt_stats"
	help=""/>
  <icon id="tt_admin" url_param="template_name=tt/new_tt_admin.html"
        rtype="tt" platform=""
	label="quick.quickview.tt_admin" tip="quick.quickview.tt_admin"
	help=""/>
  <icon id="quick_tt_admin" url_param="template_name=tt/new_tt_admin.html"
        rtype="tt" platform=""
	label="quick.quickview.tt_admin" tip="quick.quickview.tt_admin" help=""
	new_window="1"/>
  <icon id="sup_ttcenter" url_param="template_name=tt/user_view_tts.html"
	rtype="tt" platform=""
	label="quick.quickview.sup_ttcenter" tip="quick.quickview.sup_ttcenter"
	help=""/>
  <icon id="sup_newtt" url_param="template_name=tt/new_tt_form.html&amp;inPanel=0"
	rtype="tt" platform=""
	label="quick.quickview.sup_newtt" tip="quick.quickview.sup_newtt"
	help=""/>
  <icon id="ws_ssl" url_param="template_name=quick/choice_ssl.html"
	rtype="ssl;sharedssl" platform=""
	label="quick.quickview.ssl" tip="quick.quickview.ssl"
	help=""/>
  <icon id="ws_apache" url_param="template_name=quick/choice_handlers.html"
	rtype="cgi" platform=""
	label="quick.quickview.apache"
	tip="quick.quickview.apache" help=""/>
  <icon id="ws_error" url_param="template_name=quick/choice_errordoc.html"
	rtype="errordoc" platform="unix"
	label="quick.quickview.error"
	tip="quick.quickview.error" help=""/>
  <icon id="ws_mime" url_param="template_name=quick/choice_mime.html"
	rtype="mimetype" platform=""
	label="quick.quickview.mime"
	tip="quick.quickview.mime" help=""/>
  <icon id="ws_redirect" url_param="template_name=quick/choice_redirect.html"
	rtype="redirect_url" platform=""
	label="quick.quickview.redirect"
	tip="quick.quickview.altredirect" help=""/>
  <icon id="resel_change_url" url_param="template_name=replacements/reseller/misc/admin_url.html"
	rtype="reseller" platform=""
	label="quick.quickview.change_url"
	tip="quick.quickview.change_url" help=""/>
  <icon id="resel_login" url_param="template_name=replacements/reseller/misc/add_admin_account.html"
	rtype="reseller" platform=""
	label="quick.quickview.resel_login"
	tip="quick.quickview.resel_login" help=""/>
  <icon id="info_resprice" url_param="template_name=replacements/reseller/billing/reseller_price.html"
        rtype="reseller" platform=""
        label="label.reseller_prices" tip="label.reseller_prices"
        help=""/>

  <icon id="adm_info_plans" url_param="template_name=admin/plans.html"
        rtype="admin" platform=""
        label="icon.adm_info_plans_l" tip="icon.adm_info_plans_t"
        help=""/>
  <icon id="adm_info_plan_wizards" url_param="template_name=admin/wizards/list.html"
        rtype="admin" platform=""
        label="icon.adm_info_pwizards_l" tip="icon.adm_info_pwizards_t"
        help=""/>
  <icon id="adm_info_plan_cmp" url_param="template_name=admin/group_plans.html"
        rtype="admin, cmp_groups" platform=""
        label="icon.adm_info_plan_cmp_l" tip="icon.adm_info_plan_cmp_t"
        help=""/>
  <icon id="adm_info_glb_res" url_param="template_name=admin/gl_resources.html"
        rtype="reseller_su" platform=""
        label="icon.adm_info_glb_res_l" tip="icon.adm_info_glb_res_t"
        help=""/>
  <icon id="adm_3rd_party_miva_lics" url_param="template_name=admin/miva_lic_man.html"
        rtype="admin, miva_lic_manager" platform=""
        label="icon.adm_3rd_party_miva_lics_l" tip="icon.adm_3rd_party_miva_lics_t"
        help=""/>
  <icon id="adm_3rd_party_urchin_lics" url_param="template_name=admin/urchin_lic.html"
        rtype="admin, urchin_lic_manager" platform=""
        label="icon.adm_3rd_party_urchin_lics_l" tip="icon.adm_3rd_party_urchin_lics_t"
        help=""/>
  <icon id="adm_3rd_party_spamassassin_man" url_param="template_name=admin/spamassassin_manager.html"
        rtype="admin, spamassassin_manager" platform=""
        label="icon.adm_3rd_party_spamassassin_man_l" tip="icon.adm_3rd_party_spamassassin_man_t"
        help=""/>
  <icon id="adm_3rd_party_sitetoolbox" url_param="template_name=admin/sitetoolbox.html"
        rtype="admin, sitetoolboxmanager" platform=""
        label="icon.adm_3rd_party_sitetoolbox_l" tip="icon.adm_3rd_party_sitetoolbox_t"
        help=""/>
  <icon id="adm_3rd_party_kanoodle" url_param="template_name=admin/kanoodle.html"
        rtype="admin, kanoodlemanager" platform=""
        label="icon.adm_3rd_party_kanoodle_l" tip="icon.adm_3rd_party_kanoodle_t"
        help=""/>
  <icon id="adm_ssh_manager" url_param="template_name=admin/sshmanager.html"
        rtype="admin, sshmanager" platform=""
        label="icon.adm_ssh_manager_l" tip="icon.adm_ssh_manager_t"
        help=""/>
  <icon id="adm_system_info" url_param="template_name=admin/system_info.html"
        rtype="admin" platform=""
        label="icon.adm_system_info_l" tip="icon.adm_system_info_t"
        help=""/>
  <icon id="adm_enterprise_system_info" url_param="template_name=admin/all_system_info.html"
        rtype="reseller_su" platform=""
        label="icon.adm_enterprise_sysinfo_l" tip="icon.adm_enterprise_sysinfo_t"
        help=""/>

  <icon id="adm_user_pref_pass" url_param="template_name=misc/info_password_form.html"
        rtype="" platform=""
        label="icon.adm_user_pref_pass_l" tip="icon.adm_user_pref_pass_t"
        help=""/>
  <icon id="adm_user_choose_acct" url_param="template_name=misc/info_choose_account.html"
        rtype="" platform=""
        label="icon.adm_user_choose_acct_l" tip="icon.adm_user_choose_acct_t"
        help=""/>
  <icon id="adm_user_add_acct" url_param="template_name=admin/add_accounts.html"
        rtype="signupadm" platform=""
        label="icon.adm_user_add_acct_l" tip="icon.adm_user_add_acct_t"
        help=""/>

  <icon id="adm_signup_signup" url_param="template_name=admin/signup.html"
        rtype="signupadm" platform=""
        label="icon.adm_signup_signup_l" tip="icon.adm_signup_signup_t"
        help=""/>
  <icon id="adm_signup_moderate" url_param="template_name=signup/moderate.html"
        rtype="signupadm" platform=""
        label="icon.adm_signup_moderate_l" tip="icon.adm_signup_moderate_t"
        help=""/>
  <icon id="adm_signup_stats" url_param="template_name=signup/stat.html"
        rtype="signupadm" platform=""
        label="icon.adm_signup_stats_l" tip="icon.adm_signup_stats_t"
        help=""/>

  <icon id="adm_search_accounts" url_param="template_name=admin/search.html"
        rtype="admin" platform=""
        label="icon.adm_search_accounts_l" tip="icon.adm_search_accounts_t"
        help=""/>
  <icon id="adm_search_domains" url_param="template_name=admin/domains.html"
        rtype="admin" platform=""
        label="icon.adm_search_domains_l" tip="icon.adm_search_domains_t"
        help=""/>
  <icon id="adm_search_byci" url_param="template_name=admin/search_ci.html"
        rtype="admin" platform=""
        label="icon.adm_search_byci_l" tip="icon.adm_search_byci_t"
        help=""/>
  <icon id="adm_search_all" url_param="template_name=admin/search_all.html"
        rtype="reseller_su" platform=""
        label="icon.adm_search_all_l" tip="icon.adm_search_all_t"
        help=""/>
  <icon id="adm_search_suspended" url_param="template_name=admin/search_suspended.html"
        rtype="admin" platform=""
        label="icon.adm_search_suspended_l" tip="icon.adm_search_suspended_t"
        help=""/>
  <icon id="adm_search_deleted" url_param="template_name=admin/search_deleted.html"
        rtype="admin" platform=""
        label="icon.adm_search_deleted_l" tip="icon.adm_search_deleted_t"
        help=""/>
  <icon id="adm_search_vps" url_param="template_name=admin/search_vps.html"
        rtype="admin" platform=""
        label="icon.adm_search_vps_l" tip="icon.adm_search_vps_t"
        help=""/>

  <icon id="adm_info_tt" url_param="template_name=tt/admin.html"
        rtype="ttadmin" platform=""
        label="icon.adm_info_tt_l" tip="icon.adm_info_tt_t"
        help=""/>
  <icon id="adm_info_tt_search" url_param="template_name=tt/tt_search.html"
        rtype="ttadmin" platform=""
        label="icon.adm_info_tt_search_l" tip="icon.adm_info_tt_search_t"
        help=""/>
  <icon id="adm_info_make_tt" url_param="template_name=tt/new_tt_form.html&amp;inPanel=0"
        rtype="tt" platform=""
        label="icon.adm_info_make_tt_l" tip="icon.adm_info_make_tt_t"
        help=""/>
  <icon id="ttadm_info_make_tt" url_param="template_name=tt/new_tt_form.html&amp;inPanel=1"
        rtype="tt" platform=""
        label="icon.adm_info_make_tt_l" tip="icon.adm_info_make_tt_t"
        help=""/>
  <icon id="adm_acct_pref_tt" url_param="template_name=tt/user_view_tts.html"
        rtype="tt" platform=""
        label="icon.adm_acct_pref_tt_l" tip="icon.adm_acct_pref_tt_t"
        help=""/>
  <icon id="adm_info_tt_info" url_param="template_name=tt/admin_info.html"
        rtype="ttadmin" platform=""
        label="icon.adm_info_tt_info_l" tip="icon.adm_info_tt_info_t"
	help=""/>

  <icon id="adm_info_tt_custom_jobs" url_param="template_name=tt/customjobs.html"
	rtype="tt" platform=""
	label="icon.adm_info_tt_custom_jobs_l" tip="icon.adm_info_tt_custom_jobs_t"
	help=""/>

  <icon id="adm_lf_corp_img" url_param="template_name=admin/settings/corp_img_lf.html"
        rtype="admin" platform=""
        label="icon.adm_lf_corp_img_l" tip="icon.adm_lf_corp_img_t"
        help=""/>
  <icon id="adm_lf_design_settings" url_param="template_name=admin/settings/design_lf.html"
        rtype="admin" platform=""
        label="icon.adm_lf_design_settings_l" tip="icon.adm_lf_design_settings_t"
        help=""/>
  <icon id="adm_lf_company" url_param="template_name=admin/settings/info.html"
        rtype="admin" platform=""
        label="icon.adm_lf_company_l" tip="icon.adm_lf_company_t"
        help=""/>
  <icon id="adm_lf_login_texts" url_param="template_name=admin/settings/login_texts.html"
        rtype="admin" platform=""
        label="icon.adm_lf_login_texts_l" tip="icon.adm_lf_login_texts_t"
        help=""/>
  <icon id="adm_lf_signup_texts" url_param="template_name=admin/settings/signup_texts.html"
        rtype="admin" platform=""
        label="icon.adm_lf_signup_texts_l" tip="icon.adm_lf_signup_texts_t"
        help=""/>
  <icon id="adm_lf_misc_texts" url_param="template_name=admin/settings/other.html"
        rtype="admin" platform=""
        label="icon.adm_lf_misc_texts_l" tip="icon.adm_lf_misc_texts_t"
        help=""/>
  <icon id="adm_lf_langs" url_param="template_name=admin/settings/langs.html"
        rtype="admin" platform=""
        label="icon.adm_lf_langs_l" tip="icon.adm_lf_langs_t"
        help=""/>
  <icon id="adm_lf_regions" url_param="template_name=admin/settings/regions.html"
        rtype="admin" platform=""
        label="icon.adm_lf_regions_l" tip="icon.adm_lf_regions_t"
        help=""/>

  <icon id="adm_mailman_list" url_param="template_name=mailman/settings.html"
        rtype="admin" platform=""
        label="icon.adm_mailman_list_l" tip="icon.adm_mailman_list_t"
        help=""/>
  <icon id="adm_cc_brands" url_param="template_name=admin/settings/ccbrands.html"
        rtype="merchant_manager" platform=""
        label="icon.adm_cc_brands_l" tip="icon.adm_cc_brands_t"
        help=""/>
  <icon id="adm_merchant_view" url_param="template_name=admin/merchant/view.html"
        rtype="merchant_manager" platform=""
        label="icon.adm_merchant_view_l" tip="icon.adm_merchant_view_t"
        help=""/>
  <icon id="adm_domain_registrar" url_param="template_name=admin/registrar/view.html"
        rtype="admin" platform=""
        label="icon.adm_domain_registrar_l" tip="icon.adm_domain_registrar_t"
        help=""/>
  <icon id="adm_signup_guard" url_param="template_name=admin/signup_guard.html"
        rtype="admin" platform=""
        label="icon.adm_signup_guard_l" tip="icon.adm_signup_guard_t"
        help=""/>
  <icon id="adm_settings_license" url_param="template_name=admin/settings/license.html"
        rtype="reseller_su" platform=""
        label="icon.adm_settings_license_l" tip="icon.adm_settings_license_t"
        help=""/>
  <icon id="adm_settings_tt" url_param="template_name=admin/settings/tt.html"
        rtype="admin" platform=""
        label="icon.adm_settings_tt_l" tip="icon.adm_settings_tt_t"
        help=""/>
  <icon id="adm_settings_perc" url_param="template_name=admin/settings/percents.html"
        rtype="admin" platform=""
        label="icon.adm_settings_perc_l" tip="icon.adm_settings_perc_t"
        help=""/>
  <icon id="adm_settings_taxes" url_param="template_name=admin/settings/taxes.html"
        rtype="admin" platform=""
        label="icon.adm_settings_taxes_l" tip="icon.adm_settings_taxes_t"
        help=""/>
  <icon id="adm_settings_aff" url_param="template_name=admin/settings/aff.html"
        rtype="admin" platform=""
        label="icon.adm_settings_aff_l" tip="icon.adm_settings_aff_t"
        help=""/>
  <icon id="adm_suspend_debtors" url_param="template_name=admin/settings/notifications.html"
        rtype="admin" platform=""
        label="icon.adm_suspend_debtors_l" tip="icon.adm_suspend_debtors_t"
        help=""/>
  <icon id="adm_trial_warn" url_param="template_name=admin/settings/notifications_trial.html"
        rtype="admin" platform=""
        label="icon.adm_trial_warn_l" tip="icon.adm_trial_warn_t"
        help=""/>

  <icon id="adm_emanager_enterprise" url_param="template_name=eeman/list.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_enterprise_l" tip="icon.adm_emanager_enterprise_t"
        help=""/>
  <icon id="adm_emanager_pservers" url_param="template_name=eeman/pservers.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_pservers_l" tip="icon.adm_emanager_pservers_t"
        help=""/>
  <icon id="adm_emanager_add_pserver" url_param="template_name=eeman/add_pserver.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_add_pserver_l" tip="icon.adm_emanager_add_pserver_t"
        help=""/>
  <icon id="adm_emanager_lservers" url_param="template_name=eeman/lservers.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_lservers_l" tip="icon.adm_emanager_lservers_t"
        help=""/>
  <icon id="adm_emanager_add_lserver" url_param="template_name=eeman/add_lserver.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_add_lserver_l" tip="icon.adm_emanager_add_lserver_t"
        help=""/>
  <icon id="adm_emanager_server_groups" url_param="template_name=eeman/groups.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_server_groups_l" tip="icon.adm_emanager_server_groups_t"
        help=""/>
  <icon id="adm_emanager_adnsmanager" url_param="template_name=adnsmanager/list.html"
        rtype="adnsmanager" platform=""
        label="icon.adm_emanager_adnsmanager_l" tip="icon.adm_emanager_adnsmanager_t"
        help=""/>
  <icon id="adm_emanager_res" url_param="template_name=eeman/list_res.html"
        rtype="reseller_eeman" platform=""
        label="icon.adm_emanager_res_l" tip="icon.adm_emanager_res_t"
        help=""/>
  <icon id="adm_emanager_ssl" url_param="template_name=adnsmanager/listssl.html"
        rtype="adnsmanager" platform=""
        label="icon.adm_emanager_ssl_l" tip="icon.adm_emanager_ssl_t"
        help=""/>
  <icon id="adm_emanager_mservers" url_param="template_name=eeman/mservers.html"
        rtype="eeman" platform=""
        label="icon.adm_emanager_mservers_l" tip="icon.adm_emanager_mservers_t"
        help=""/>
  <icon id="adm_emanager_cmove" url_param="template_name=eeman/cmove.html"